export const SUBJECTS = [
  'Mathematics',
  'Science',
  'Computing',
  'English',
  'Social Studies',
  'French',
  'Ghanaian Language',
  'History',
  'Our World and Our People',
  'Creative Arts',
  'Physical Education',
  'Religious and Moral Education',
  'Career Technology',
  'Arabic',
  'Mixed',
  'Physics',
  'Chemistry',
  'Biology',
  'ICT',
  'Elective Mathematics',
  'Economics',
  'Government',
  'Geography',
  'Agricultural Science',
]

export const BADGE_SUBJECT_MAP = {
  mathematics: 'subject_math',
  science: 'subject_sci',
  computing: 'subject_comp',
  english: 'subject_eng',
  'social studies': 'subject_sst',
  french: 'subject_fr',
  'ghanaian language': 'subject_gl',
  history: 'subject_hist',
  'our world and our people': 'subject_owwop',
  'creative arts': 'subject_ca',
  'physical education': 'subject_pe',
  'religious and moral education': 'subject_rme',
  'career technology': 'subject_ct',
  arabic: 'subject_ar',
  physics: 'subject_physics',
  chemistry: 'subject_chem',
  biology: 'subject_bio',
  ict: 'subject_comp',
}
