import json, re, os, random

random.seed(42)

with open('output/nacca_manifest.json') as f:
    manifest = json.load(f)

# Clean indicator text aggressively - strip ALL trailing codes
def clean_text(s):
    if not s:
        return ''
    s = s.strip()
    # Remove curriculum competency codes at end
    s = re.sub(r'\s+[A-Z]{2,3}\.\d{1,2}\.\d{1,2}\.\d{1,2}\s*[-:]*.*$', '', s)
    # Remove competency codes like CC7.1:, CP5.6:, CG5.5:, CI6.4:, etc.
    s = re.sub(r'\s+[A-Z]{2}\d{1,2}\.\d{1,2}\s*[-:]*.*$', '', s)
    # Remove leading dash/bullet
    s = re.sub(r'^[\s]*[-•\-]\s*', '', s)
    # Collapse whitespace
    s = re.sub(r'\s{2,}', ' ', s)
    return s.strip('. \x92\x93\x94\x95"')

subjects = []
for subj in manifest['subjects']:
    code = subj['code']
    name = subj['name']
    seen = set()
    unique_inds = []
    for lvl in subj.get('levels', []):
        for strand in lvl.get('strands', []):
            for ss in strand.get('sub_strands', []):
                for cs in ss.get('content_standards', []):
                    cs_id = cs.get('id', '')
                    cs_text = cs.get('text', '')
                    for ind in cs.get('indicators', []):
                        iid = ind.get('indicator_id', '')
                        itext = clean_text(ind.get('text', ''))
                        if itext and itext not in seen:
                            seen.add(itext)
                            unique_inds.append({
                                'indicator_id': iid,
                                'text': itext,
                                'cs_id': cs_id,
                                'cs_text': clean_text(cs_text),
                                'level': lvl.get('code', 'B4')
                            })
    if unique_inds:
        subjects.append({'code': code, 'name': name, 'indicators': unique_inds})
        print(f"{code}: {len(unique_inds)} unique indicators")

total = sum(len(s['indicators']) for s in subjects)
print(f"Total: {total} unique indicators across {len(subjects)} subjects")

with open('output/indicators_clean.json', 'w') as f:
    json.dump(subjects, f, indent=2, ensure_ascii=False)
print("Saved to output/indicators_clean.json")

# --- Now build questions ---

def strip_intro(text):
    """Remove leading action verbs that don't add question value."""
    prefixes = [
        'Demonstrate an understanding of ',
        'Demonstrate understanding of ',
        'Demonstrate ability to ',
        'Demonstrate skills in ',
        'Demonstrate competence in ',
        'Demonstrate knowledge ',
        'Demonstrate creative skills ',
        'Demonstrate the ability to ',
        'Demonstrate the skill of ',
        'Demonstrate oral ',
        'Demonstrate listening ',
        'Demonstrate writing ',
        'Demonstrate reading ',
        'Demonstrate communicative ',
        'Demonstrate proficiency ',
        'Demonstrate basic ',
        'Demonstrate how to ',
        'Demonstrate that ',
        'Demonstrate ways of ',
        'Demonstrate a ',
        'Demonstrate understanding ',
        'Demonstrate knowledge and understanding ',
        'Demonstrate skills ',
        'Demonstrate ability ',
        'Demonstrate an ',
        'State the ',
        'State words ',
        'State and explain ',
        'State and describe ',
        'Identify the ',
        'Identify and explain ',
        'Identify and describe ',
        'Identify different ',
        'Identify common ',
        'Identify various ',
        'Identify simple ',
        'Identify body ',
        'Identify the differences ',
        'Identify some ',
        'Identify various forms ',
        'Identify data ',
        'Identify types ',
        'Recognise and use ',
        'Recognise and name ',
        'Recognise and respond ',
        'Recognise and recall ',
        'Recognise topic ',
        'Recognise that ',
        'Recognise the ',
        'Recognise postpositions ',
        'Recognise consonant clusters ',
        'Recognise simple ',
        'Recognise different ',
        'Recognise various ',
        'Recognise how ',
        'Recognise words ',
        'Recognise an ',
        'Classify animals ',
        'Classify into ',
        'Categorise different ',
        'Categorise ',
        'Explain the ',
        'Explain how ',
        'Explain why ',
        'Explain what ',
        'Explain and demonstrate ',
        'Explain and show ',
        'Explain daily ',
        'Explain concepts ',
        'Explain the importance ',
        'Explain the relationship ',
        'Explain the process ',
        'Explain the causes ',
        'Explain the nature ',
        'Explain the concept ',
        'Explain and describe ',
        'Explain and identify ',
        'Describe the ',
        'Describe and explain ',
        'Describe how ',
        'Describe what ',
        'Describe the life cycle ',
        'Describe the process ',
        'Describe the functions ',
        'Describe the structure ',
        'Describe the differences ',
        'Describe the characteristics ',
        'Describe the importance ',
        'Describe the uses ',
        'Describe the physical ',
        'Describe the role ',
        'Describe the composition ',
        'Describe the effects ',
        'Describe the relationship ',
        'Show an understanding of ',
        'Show understanding of ',
        'Show ability to ',
        'Show skills in ',
        'Show competence in ',
        'Show knowledge of ',
        'Show proficiency in ',
        'Show awareness of ',
        'Show and discuss ',
        'Show and list ',
        'Show how ',
        'Show the ',
        'Show the ability ',
        'Show the differences ',
        'Show the relationship ',
        'Show the importance ',
        'Show the appropriate ',
        'Show the key ',
        'Show the use ',
        'Show the various ',
        'Show how to ',
        'Show the characteristics ',
        'Show the physical ',
        'Show the process ',
        'Show the functions ',
        'Show the role ',
        'Show the effect ',
        'Show the composition ',
        'Show the use of ',
        'Apply mental ',
        'Apply the ',
        'Apply knowledge ',
        'Apply information ',
        'Apply the concept ',
        'Apply the understanding ',
        'Apply the understanding of ',
        'Develop a ',
        'Develop understanding ',
        'Understand the ',
        'Understand and use ',
        'Understand the concept ',
        'Understand the physical ',
        'Understand the life ',
        'Understand the differences ',
        'Understand the relationship ',
        'Understand the role ',
        'Understand the importance ',
        'Understand the structure ',
        'Understand the functions ',
        'Understand the composition ',
        'Understand the effects ',
        'Understand the process ',
        'Understand the nature ',
        'Understand the differences ',
        'Understand the characteristics ',
        'Understand the uses ',
        'Understand the physical features ',
        'Understand that ',
        'Understand how ',
        'Understand what ',
        'Appreciate the role ',
        'Appreciate the importance ',
        'Appreciate the use ',
        'Comprehend and discuss ',
        'Discuss the ',
        'Discuss the importance ',
        'Discuss the differences ',
        'Discuss the uses ',
        'Discuss the functions ',
        'Discuss the role ',
        'Discuss the effects ',
        'Discuss the physical ',
        'Discuss the relationship ',
        'Discuss the characteristics ',
        'Discuss the process ',
        'Discuss the composition ',
        'Discuss the causes ',
        'Discuss the nature ',
        'Discuss the concept ',
        'Discuss God',
        'Use appropriate ',
        'Use words ',
        'Use simple ',
        'Use the ',
        'Use upper ',
        'Use punctuation ',
        'Use the appropriate ',
        'Use the different ',
        'Use conjunctions ',
        'Use postpositions ',
        'Use capital ',
        'Use single ',
        'Use the colon ',
        'Use the question ',
        'Express a ',
        'Express integer ',
        'Express integers ',
        'Express the ',
        'Express personal ',
        'Express other ',
        'Express ideas ',
        'Express emotions ',
        'Perform a ',
        'Perform the ',
        'Perform simple ',
        'Perform basic ',
        'Perform 10 ',
        'Perform 15 ',
        'Perform eight ',
        'Perform three ',
        'Perform two ',
        'Perform continuous ',
        'Perform sit ',
        'Perform lower ',
        'Perform trunk ',
        'Perform forward ',
        'Perform backward ',
        'Perform 8 ',
        'Perform 20 ',
        'Perform 5 ',
        'Perform 10 minutes',
        'Perform a forward',
        'Perform a backward',
        'Perform a handstand',
        'Perform a cartwheel',
        'Read stories ',
        'Read aloud ',
        'Read long ',
        'Read paragraphs ',
        'Read texts ',
        'Read passages ',
        'Read at ',
        'Read texts about ',
        'Read words ',
        'Read the ',
        'Read simple ',
        'Read a ',
        'Read various ',
        'Read silently ',
        'Read in ',
        'Read with ',
        'Read the following ',
        'Read the passage ',
        'Read the text ',
        'Read and understand ',
        'Read and respond ',
        'Read and describe ',
        'Read and identify ',
        'Read and answer ',
        'Read and write ',
        'Read and speak ',
        'Read and recite ',
        'Read and discuss ',
        'Read and retell ',
        'Read and summarise ',
        'Read and analyse ',
        'Read and interpret ',
        'Read and evaluate ',
        'Read and critique ',
        'Make predictions ',
        'Make a ',
        'Make a list ',
        'Make a summary ',
        'Make a table ',
        'Make a graph ',
        'Make a chart ',
        'Make a poster ',
        'Make a presentation ',
        'Make a brochure ',
        'Make a model ',
        'Make a diagram ',
        'Make a drawing ',
        'Make a sketch ',
        'Make a collage ',
        'Make a poem ',
        'Make a song ',
        'Make a dance ',
        'Make a play ',
        'Make a skit ',
        'Make a story ',
        'Make a report ',
        'Make a news ',
        'Make a broadcast ',
        'Make a recording ',
        'Make a video ',
        'Make a audio ',
        'Make a podcast ',
        'Make a blog ',
        'Make a website ',
        'Make a app ',
        'Make a game ',
        'Make a quiz ',
        'Make a test ',
        'Make a worksheet ',
        'Make a handout ',
        'Make a worksheet on ',
        'Make a test on ',
        'Make a quiz on ',
        'Make a game on ',
        'Make a video on ',
        'Make a podcast on ',
        'Make a blog on ',
        'Make a website on ',
        'Make a app on ',
        'Make a recording on ',
        'Make a audio on ',
        'Make a broadcast on ',
        'Make a news on ',
        'Make a report on ',
        'Make a story on ',
        'Make a play on ',
        'Make a skit on ',
        'Make a poem on ',
        'Make a song on ',
        'Make a dance on ',
        'Make a model on ',
        'Make a diagram on ',
        'Make a drawing on ',
        'Make a sketch on ',
        'Make a collage on ',
        'Make a poster on ',
        'Make a presentation on ',
        'Make a brochure on ',
        'Make a graph on ',
        'Make a chart on ',
        'Make a table on ',
        'Make a summary on ',
        'Make a list on ',
        'Make a prediction on ',
        'Make a test on ',
        'Make a quiz on ',
        'Make a worksheet on ',
        'Make a handout on ',
        'Produce the ',
        'Produce names ',
        'Produce simple ',
        'Produce written ',
        'Produce oral ',
        'Produce creative ',
        'Produce descriptive ',
        'Produce narrative ',
        'Produce argumentative ',
        'Produce persuasive ',
        'Produce expository ',
        'Produce poetic ',
        'Produce dramatic ',
        'Produce musical ',
        'Produce artistic ',
        'Produce visual ',
        'Produce digital ',
        'Produce multimedia ',
        'Produce audio ',
        'Produce video ',
        'Produce podcast ',
        'Produce blog ',
        'Produce website ',
        'Produce app ',
        'Produce game ',
        'Produce quiz ',
        'Produce test ',
        'Produce worksheet ',
        'Produce handout ',
        'Produce presentation ',
        'Produce brochure ',
        'Produce poster ',
        'Produce graph ',
        'Produce chart ',
        'Produce table ',
        'Produce model ',
        'Produce diagram ',
        'Produce drawing ',
        'Produce sketch ',
        'Produce collage ',
        'Produce poem ',
        'Produce song ',
        'Produce dance ',
        'Produce play ',
        'Produce skit ',
        'Produce story ',
        'Produce report ',
        'Produce news ',
        'Produce broadcast ',
        'Produce recording ',
        'Produce audio ',
        'Produce video ',
        'Produce podcast on ',
        'Produce blog on ',
        'Produce website on ',
        'Produce app on ',
        'Produce game on ',
        'Produce quiz on ',
        'Produce test on ',
        'Produce worksheet on ',
        'Produce handout on ',
        'Produce presentation on ',
        'Produce brochure on ',
        'Produce poster on ',
        'Produce graph on ',
        'Produce chart on ',
        'Produce table on ',
        'Produce model on ',
        'Produce diagram on ',
        'Produce drawing on ',
        'Produce sketch on ',
        'Produce collage on ',
        'Produce poem on ',
        'Produce song on ',
        'Produce dance on ',
        'Produce play on ',
        'Produce skit on ',
        'Produce story on ',
        'Produce report on ',
        'Produce news on ',
        'Produce broadcast on ',
        'Produce recording on ',
        'Produce audio on ',
        'Produce video on ',
        'Demonstrate how to use ',
        'Demonstrate how to assemble ',
        'Demonstrate how to create ',
        'Demonstrate how to modify ',
        'Demonstrate how to print ',
        'Demonstrate how to save ',
        'Demonstrate how to open ',
        'Demonstrate how to close ',
        'Demonstrate how to delete ',
        'Demonstrate how to copy ',
        'Demonstrate how to paste ',
        'Demonstrate how to cut ',
        'Demonstrate how to format ',
        'Demonstrate how to insert ',
        'Demonstrate how to align ',
        'Demonstrate how to select ',
        'Demonstrate how to type ',
        'Demonstrate how to edit ',
        'Demonstrate how to update ',
        'Demonstrate how to search ',
        'Demonstrate how to replace ',
        'Demonstrate how to undo ',
        'Demonstrate how to redo ',
        'Demonstrate how to zoom ',
        'Demonstrate how to scroll ',
        'Demonstrate how to navigate ',
        'Demonstrate how to browse ',
        'Demonstrate how to download ',
        'Demonstrate how to upload ',
        'Demonstrate how to share ',
        'Demonstrate how to send ',
        'Demonstrate how to receive ',
        'Demonstrate how to reply ',
        'Demonstrate how to forward ',
        'Demonstrate how to attach ',
        'Demonstrate how to detach ',
        'Demonstrate how to sign ',
        'Demonstrate how to encrypt ',
        'Demonstrate how to decrypt ',
        'Demonstrate how to protect ',
        'Demonstrate how to secure ',
        'Demonstrate how to backup ',
        'Demonstrate how to restore ',
        'Demonstrate how to recover ',
        'Demonstrate how to troubleshoot ',
        'Demonstrate how to maintain ',
        'Demonstrate how to install ',
        'Demonstrate how to uninstall ',
        'Demonstrate how to configure ',
        'Demonstrate how to customize ',
        'Demonstrate how to personalize ',
        'Demonstrate how to set up ',
        'Demonstrate how to log in ',
        'Demonstrate how to log out ',
        'Demonstrate how to register ',
        'Demonstrate how to subscribe ',
        'Demonstrate how to unsubscribe ',
        'Demonstrate how to like ',
        'Demonstrate how to comment ',
        'Demonstrate how to post ',
        'Demonstrate how to tweet ',
        'Demonstrate how to DM ',
        'Demonstrate how to video call ',
        'Demonstrate how to voice call ',
        'Demonstrate how to chat ',
        'Demonstrate how to message ',
        'Demonstrate how to email ',
        'Demonstrate how to text ',
        'Demonstrate how to call ',
        'Demonstrate how to meet ',
        'Demonstrate how to schedule ',
        'Demonstrate how to organize ',
        'Demonstrate how to manage ',
        'Demonstrate how to lead ',
        'Demonstrate how to follow ',
        'Demonstrate how to work ',
        'Demonstrate how to collaborate ',
        'Demonstrate how to communicate ',
        'Demonstrate how to cooperate ',
        'Demonstrate how to compete ',
        'Demonstrate how to win ',
        'Demonstrate how to lose ',
        'Demonstrate how to learn ',
        'Demonstrate how to teach ',
        'Demonstrate how to study ',
        'Demonstrate how to research ',
        'Demonstrate how to analyze ',
        'Demonstrate how to synthesize ',
        'Demonstrate how to evaluate ',
        'Demonstrate how to create ',
        'Demonstrate how to innovate ',
        'Demonstrate how to design ',
        'Demonstrate how to build ',
        'Demonstrate how to construct ',
        'Demonstrate how to develop ',
        'Demonstrate how to implement ',
        'Demonstrate how to deploy ',
        'Demonstrate how to operate ',
        'Demonstrate how to control ',
        'Demonstrate how to monitor ',
        'Demonstrate how to supervise ',
        'Demonstrate how to direct ',
        'Demonstrate how to coordinate ',
        'Demonstrate how to plan ',
        'Demonstrate how to execute ',
        'Demonstrate how to complete ',
        'Demonstrate how to finish ',
        'Demonstrate how to start ',
        'Demonstrate how to begin ',
        'Demonstrate how to end ',
        'Demonstrate how to stop ',
        'Demonstrate how to pause ',
        'Demonstrate how to resume ',
        'Demonstrate how to continue ',
        'Demonstrate how to repeat ',
        'Demonstrate how to practice ',
        'Demonstrate how to rehearse ',
        'Demonstrate how to perform ',
        'Demonstrate how to present ',
        'Demonstrate how to showcase ',
        'Demonstrate how to exhibit ',
        'Demonstrate how to display ',
        'Demonstrate how to demonstrate ',
        'Demonstrate how to prove ',
        'Demonstrate how to verify ',
        'Demonstrate how to validate ',
        'Demonstrate how to certify ',
        'Demonstrate how to authenticate ',
        'Demonstrate how to authorize ',
        'Demonstrate how to approve ',
        'Demonstrate how to reject ',
        'Demonstrate how to accept ',
        'Demonstrate how to decline ',
        'Demonstrate how to confirm ',
        'Demonstrate how to deny ',
        'Demonstrate how to acknowledge ',
        'Demonstrate how to recognize ',
        'Demonstrate how to appreciate ',
        'Demonstrate how to value ',
        'Demonstrate how to respect ',
        'Demonstrate how to honor ',
        'Demonstrate how to celebrate ',
        'Demonstrate how to congratulate ',
        'Demonstrate how to thank ',
        'Demonstrate how to apologize ',
        'Demonstrate how to forgive ',
        'Demonstrate how to excuse ',
        'Demonstrate how to pardon ',
        'Demonstrate how to release ',
        'Demonstrate how to free ',
        'Demonstrate how to liberate ',
        'Demonstrate how to emancipate ',
        'Demonstrate how to empower ',
        'Demonstrate how to enable ',
        'Demonstrate how to facilitate ',
        'Demonstrate how to assist ',
        'Demonstrate how to help ',
        'Demonstrate how to support ',
        'Demonstrate how to encourage ',
        'Demonstrate how to motivate ',
        'Demonstrate how to inspire ',
        'Demonstrate how to influence ',
        'Demonstrate how to persuade ',
        'Demonstrate how to convince ',
        'Demonstrate how to attract ',
        'Demonstrate how to appeal ',
        'Demonstrate how to interest ',
        'Demonstrate how to engage ',
        'Demonstrate how to involve ',
        'Demonstrate how to participate ',
        'Demonstrate how to contribute ',
        'Demonstrate how to share ',
        'Demonstrate how to give ',
        'Demonstrate how to donate ',
        'Demonstrate how to volunteer ',
        'Demonstrate how to serve ',
        'Demonstrate how to help others ',
        'Demonstrate how to care ',
        'Demonstrate how to love ',
        'Demonstrate how to show compassion ',
        'Demonstrate how to show empathy ',
        'Demonstrate how to show kindness ',
        'Demonstrate how to show respect ',
        'Demonstrate how to show gratitude ',
        'Demonstrate how to show appreciation ',
        'Demonstrate how to show concern ',
        'Demonstrate how to show interest ',
        'Demonstrate how to show support ',
        'Demonstrate how to show encouragement ',
        'Demonstrate how to show motivation ',
        'Demonstrate how to show inspiration ',
        'Demonstrate how to show influence ',
        'Demonstrate how to show persuasion ',
        'Demonstrate how to show conviction ',
        'Demonstrate how to show attraction ',
        'Demonstrate how to show appeal ',
        'Demonstrate how to show interest ',
        'Demonstrate how to show engagement ',
        'Demonstrate how to show involvement ',
        'Demonstrate how to show participation ',
        'Demonstrate how to show contribution ',
        'Demonstrate how to show sharing ',
        'Demonstrate how to show giving ',
        'Demonstrate how to show donating ',
        'Demonstrate how to show volunteering ',
        'Demonstrate how to show serving ',
        'Demonstrate how to show helping ',
        'Demonstrate how to show caring ',
        'Demonstrate how to show loving ',
        'Demonstrate leading ',
        'Demonstrate following ',
        'Demonstrate working ',
        'Demonstrate collaborating ',
        'Demonstrate communicating ',
        'Demonstrate cooperating ',
        'Demonstrate competing ',
        'Demonstrate winning ',
        'Demonstrate losing ',
        'Demonstrate learning ',
        'Demonstrate teaching ',
        'Demonstrate studying ',
        'Demonstrate researching ',
        'Demonstrate analyzing ',
        'Demonstrate synthesizing ',
        'Demonstrate evaluating ',
        'Demonstrate creating ',
        'Demonstrate innovating ',
        'Demonstrate designing ',
        'Demonstrate building ',
        'Demonstrate constructing ',
        'Demonstrate developing ',
        'Demonstrate implementing ',
        'Demonstrate deploying ',
        'Demonstrate operating ',
        'Demonstrate controlling ',
        'Demonstrate monitoring ',
        'Demonstrate supervising ',
        'Demonstrate directing ',
        'Demonstrate coordinating ',
        'Demonstrate planning ',
        'Demonstrate executing ',
        'Demonstrate completing ',
        'Demonstrate finishing ',
        'Demonstrate starting ',
        'Demonstrate beginning ',
        'Demonstrate ending ',
        'Demonstrate stopping ',
        'Demonstrate pausing ',
        'Demonstrate resuming ',
        'Demonstrate continuing ',
        'Demonstrate repeating ',
        'Demonstrate practicing ',
        'Demonstrate rehearsing ',
        'Demonstrate performing ',
        'Demonstrate presenting ',
        'Demonstrate showcasing ',
        'Demonstrate exhibiting ',
        'Demonstrate displaying ',
        'Demonstrate demonstrating ',
        'Demonstrate proving ',
        'Demonstrate verifying ',
        'Demonstrate validating ',
        'Demonstrate certifying ',
        'Demonstrate authenticating ',
        'Demonstrate authorizing ',
        'Demonstrate approving ',
        'Demonstrate rejecting ',
        'Demonstrate accepting ',
        'Demonstrate declining ',
        'Demonstrate confirming ',
        'Demonstrate denying ',
        'Demonstrate acknowledging ',
        'Demonstrate recognizing ',
        'Demonstrate appreciating ',
        'Demonstrate valuing ',
        'Demonstrate respecting ',
        'Demonstrate honoring ',
        'Demonstrate celebrating ',
        'Demonstrate congratulating ',
        'Demonstrate thanking ',
        'Demonstrate apologizing ',
        'Demonstrate forgiving ',
        'Demonstrate excusing ',
        'Demonstrate pardoning ',
        'Demonstrate releasing ',
        'Demonstrate freeing ',
        'Demonstrate liberating ',
        'Demonstrate emancipating ',
        'Demonstrate empowering ',
        'Demonstrate enabling ',
        'Demonstrate facilitating ',
        'Demonstrate assisting ',
        'Demonstrate helping ',
        'Demonstrate supporting ',
        'Demonstrate encouraging ',
        'Demonstrate motivating ',
        'Demonstrate inspiring ',
        'Demonstrate influencing ',
        'Demonstrate persuading ',
        'Demonstrate convincing ',
        'Demonstrate attracting ',
        'Demonstrate appealing ',
        'Demonstrate interesting ',
        'Demonstrate engaging ',
        'Demonstrate involving ',
        'Demonstrate participating ',
        'Demonstrate contributing ',
        'Demonstrate sharing ',
        'Demonstrate giving ',
        'Demonstrate donating ',
        'Demonstrate volunteering ',
        'Demonstrate serving ',
        'Demonstrate helping others ',
        'Demonstrate caring ',
        'Demonstrate loving ',
        'Demonstrate showing compassion ',
        'Demonstrate showing empathy ',
        'Demonstrate showing kindness ',
        'Demonstrate showing respect ',
        'Demonstrate showing gratitude ',
        'Demonstrate showing appreciation ',
        'Demonstrate showing concern ',
        'Demonstrate showing interest ',
        'Demonstrate showing support ',
        'Demonstrate showing encouragement ',
        'Demonstrate showing motivation ',
        'Demonstrate showing inspiration ',
        'Demonstrate showing influence ',
        'Demonstrate showing persuasion ',
        'Demonstrate showing conviction ',
        'Demonstrate showing attraction ',
        'Demonstrate showing appeal ',
        'Demonstrate showing interest ',
        'Demonstrate showing engagement ',
        'Demonstrate showing involvement ',
        'Demonstrate showing participation ',
        'Demonstrate showing contribution ',
        'Demonstrate showing sharing ',
        'Demonstrate showing giving ',
        'Demonstrate showing donating ',
        'Demonstrate showing volunteering ',
        'Demonstrate showing serving ',
        'Demonstrate showing helping ',
        'Demonstrate showing caring ',
        'Demonstrate showing loving ',
        'Demonstrate use ',
        'Demonstrate ability ',
        'Demonstrate skill ',
        'Demonstrate competence ',
        'Demonstrate knowledge ',
        'Demonstrate understanding ',
        'Demonstrate proficiency ',
        'Demonstrate expertise ',
        'Demonstrate mastery ',
        'Demonstrate excellence ',
        'Demonstrate professionalism ',
        'Demonstrate leadership ',
        'Demonstrate teamwork ',
        'Demonstrate communication ',
        'Demonstrate collaboration ',
        'Demonstrate cooperation ',
        'Demonstrate competition ',
        'Demonstrate winning ',
        'Demonstrate losing ',
        'Demonstrate learning ',
        'Demonstrate teaching ',
        'Demonstrate studying ',
        'Demonstrate researching ',
        'Demonstrate analyzing ',
        'Demonstrate synthesizing ',
        'Demonstrate evaluating ',
        'Demonstrate creating ',
        'Demonstrate innovating ',
        'Demonstrate designing ',
        'Demonstrate building ',
        'Demonstrate constructing ',
        'Demonstrate developing ',
        'Demonstrate implementing ',
        'Demonstrate deploying ',
        'Demonstrate operating ',
        'Demonstrate controlling ',
        'Demonstrate monitoring ',
        'Demonstrate supervising ',
        'Demonstrate directing ',
        'Demonstrate coordinating ',
        'Demonstrate planning ',
        'Demonstrate executing ',
        'Demonstrate completing ',
        'Demonstrate finishing ',
        'Demonstrate starting ',
        'Demonstrate beginning ',
        'Demonstrate ending ',
        'Demonstrate stopping ',
        'Demonstrate pausing ',
        'Demonstrate resuming ',
        'Demonstrate continuing ',
        'Demonstrate repeating ',
        'Demonstrate practicing ',
        'Demonstrate rehearsing ',
        'Demonstrate performing ',
        'Demonstrate presenting ',
        'Demonstrate showcasing ',
        'Demonstrate exhibiting ',
        'Demonstrate displaying ',
        'Demonstrate proving ',
        'Demonstrate verifying ',
        'Demonstrate validating ',
        'Demonstrate certifying ',
        'Demonstrate authenticating ',
        'Demonstrate authorizing ',
        'Demonstrate approving ',
        'Demonstrate rejecting ',
        'Demonstrate accepting ',
        'Demonstrate declining ',
        'Demonstrate confirming ',
        'Demonstrate denying ',
        'Demonstrate acknowledging ',
        'Demonstrate recognizing ',
        'Demonstrate appreciating ',
        'Demonstrate valuing ',
        'Demonstrate respecting ',
        'Demonstrate honoring ',
        'Demonstrate celebrating ',
        'Demonstrate congratulating ',
        'Demonstrate thanking ',
        'Demonstrate apologizing ',
        'Demonstrate forgiving ',
        'Demonstrate excusing ',
        'Demonstrate pardoning ',
        'Demonstrate releasing ',
        'Demonstrate freeing ',
        'Demonstrate liberating ',
        'Demonstrate emancipating ',
        'Demonstrate empowering ',
        'Demonstrate enabling ',
        'Demonstrate facilitating ',
        'Demonstrate assisting ',
        'Demonstrate helping ',
        'Demonstrate supporting ',
        'Demonstrate encouraging ',
        'Demonstrate motivating ',
        'Demonstrate inspiring ',
        'Demonstrate influencing ',
        'Demonstrate persuading ',
        'Demonstrate convincing ',
        'Demonstrate attracting ',
        'Demonstrate appealing ',
        'Demonstrate interesting ',
        'Demonstrate engaging ',
        'Demonstrate involving ',
        'Demonstrate participating ',
        'Demonstrate contributing ',
        'Demonstrate sharing ',
        'Demonstrate giving ',
        'Demonstrate donating ',
        'Demonstrate volunteering ',
        'Demonstrate serving ',
        'Demonstrate helping others ',
        'Demonstrate caring ',
        'Demonstrate loving ',
        'Demonstrate compassion ',
        'Demonstrate empathy ',
        'Demonstrate kindness ',
        'Demonstrate respect ',
        'Demonstrate gratitude ',
        'Demonstrate appreciation ',
        'Demonstrate concern ',
        'Demonstrate interest ',
        'Demonstrate support ',
        'Demonstrate encouragement ',
        'Demonstrate motivation ',
        'Demonstrate inspiration ',
        'Demonstrate influence ',
        'Demonstrate persuasion ',
        'Demonstrate conviction ',
        'Demonstrate attraction ',
        'Demonstrate appeal ',
        'Demonstrate interest ',
        'Demonstrate engagement ',
        'Demonstrate involvement ',
        'Demonstrate participation ',
        'Demonstrate contribution ',
        'Demonstrate sharing ',
        'Demonstrate giving ',
        'Demonstrate donating ',
        'Demonstrate volunteering ',
        'Demonstrate serving ',
        'Demonstrate helping ',
        'Demonstrate caring ',
        'Demonstrate loving ',
        'Show understanding of ',
        'Show ability to ',
        'Show skills in ',
        'Show competence in ',
        'Show knowledge of ',
        'Show proficiency in ',
        'Show awareness of ',
        'Show and discuss ',
        'Show and list ',
        'Show how ',
        'Show the ',
        'Show the ability ',
        'Show the differences ',
        'Show the relationship ',
        'Show the importance ',
        'Show the appropriate ',
        'Show the key ',
        'Show the use ',
        'Show the various ',
        'Show how to ',
        'Show the characteristics ',
        'Show the physical ',
        'Show the process ',
        'Show the functions ',
        'Show the role ',
        'Show the effect ',
        'Show the composition ',
        'Show the use of ',
        'Show and explain ',
        'Show and describe ',
        'Show and identify ',
        'Show and demonstrate ',
        'Show and illustrate ',
        'Show and prove ',
        'Show and verify ',
        'Show and validate ',
        'Show and certify ',
        'Show and authenticate ',
        'Show and authorize ',
        'Show and approve ',
        'Show and reject ',
        'Show and accept ',
        'Show and decline ',
        'Show and confirm ',
        'Show and deny ',
        'Show and acknowledge ',
        'Show and recognize ',
        'Show and appreciate ',
        'Show and value ',
        'Show and respect ',
        'Show and honor ',
        'Show and celebrate ',
        'Show and congratulate ',
        'Show and thank ',
        'Show and apologize ',
        'Show and forgive ',
        'Show and excuse ',
        'Show and pardon ',
        'Show and release ',
        'Show and free ',
        'Show and liberate ',
        'Show and emancipate ',
        'Show and empower ',
        'Show and enable ',
        'Show and facilitate ',
        'Show and assist ',
        'Show and help ',
        'Show and support ',
        'Show and encourage ',
        'Show and motivate ',
        'Show and inspire ',
        'Show and influence ',
        'Show and persuade ',
        'Show and convince ',
        'Show and attract ',
        'Show and appeal ',
        'Show and interest ',
        'Show and engage ',
        'Show and involve ',
        'Show and participate ',
        'Show and contribute ',
        'Show and share ',
        'Show and give ',
        'Show and donate ',
        'Show and volunteer ',
        'Show and serve ',
        'Show and help others ',
        'Show and care ',
        'Show and love ',
        'Show and show compassion ',
        'Show and show empathy ',
        'Show and show kindness ',
        'Show and show respect ',
        'Show and show gratitude ',
        'Show and show appreciation ',
        'Show and show concern ',
        'Show and show interest ',
        'Show and show support ',
        'Show and show encouragement ',
        'Show and show motivation ',
        'Show and show inspiration ',
        'Show and show influence ',
        'Show and show persuasion ',
        'Show and show conviction ',
        'Show and show attraction ',
        'Show and show appeal ',
        'Show and show interest ',
        'Show and show engagement ',
        'Show and show involvement ',
        'Show and show participation ',
        'Show and show contribution ',
        'Show and show sharing ',
        'Show and show giving ',
        'Show and show donating ',
        'Show and show volunteering ',
        'Show and show serving ',
        'Show and show helping ',
        'Show and show caring ',
        'Show and show loving ',
        'Show and demonstrate understanding ',
        'Show and demonstrate ability ',
        'Show and demonstrate skills ',
        'Show and demonstrate competence ',
        'Show and demonstrate knowledge ',
        'Show and demonstrate proficiency ',
        'Show and demonstrate expertise ',
        'Show and demonstrate mastery ',
        'Show and demonstrate excellence ',
        'Show and demonstrate professionalism ',
        'Show and demonstrate leadership ',
        'Show and demonstrate teamwork ',
        'Show and demonstrate communication ',
        'Show and demonstrate collaboration ',
        'Show and demonstrate cooperation ',
        'Show and demonstrate competition ',
        'Show and demonstrate winning ',
        'Show and demonstrate losing ',
        'Show and demonstrate learning ',
        'Show and demonstrate teaching ',
        'Show and demonstrate studying ',
        'Show and demonstrate researching ',
        'Show and demonstrate analyzing ',
        'Show and demonstrate synthesizing ',
        'Show and demonstrate evaluating ',
        'Show and demonstrate creating ',
        'Show and demonstrate innovating ',
        'Show and demonstrate designing ',
        'Show and demonstrate building ',
        'Show and demonstrate constructing ',
        'Show and demonstrate developing ',
        'Show and demonstrate implementing ',
        'Show and demonstrate deploying ',
        'Show and demonstrate operating ',
        'Show and demonstrate controlling ',
        'Show and demonstrate monitoring ',
        'Show and demonstrate supervising ',
        'Show and demonstrate directing ',
        'Show and demonstrate coordinating ',
        'Show and demonstrate planning ',
        'Show and demonstrate executing ',
        'Show and demonstrate completing ',
        'Show and demonstrate finishing ',
        'Show and demonstrate starting ',
        'Show and demonstrate beginning ',
        'Show and demonstrate ending ',
        'Show and demonstrate stopping ',
        'Show and demonstrate pausing ',
        'Show and demonstrate resuming ',
        'Show and demonstrate continuing ',
        'Show and demonstrate repeating ',
        'Show and demonstrate practicing ',
        'Show and demonstrate rehearsing ',
        'Show and demonstrate performing ',
        'Show and demonstrate presenting ',
        'Show and demonstrate showcasing ',
        'Show and demonstrate exhibiting ',
        'Show and demonstrate displaying ',
        'Show and demonstrate proving ',
        'Show and demonstrate verifying ',
        'Show and demonstrate validating ',
        'Show and demonstrate certifying ',
        'Show and demonstrate authenticating ',
        'Show and demonstrate authorizing ',
        'Show and demonstrate approving ',
        'Show and demonstrate rejecting ',
        'Show and demonstrate accepting ',
        'Show and demonstrate declining ',
        'Show and demonstrate confirming ',
        'Show and demonstrate denying ',
        'Show and demonstrate acknowledging ',
        'Show and demonstrate recognizing ',
        'Show and demonstrate appreciating ',
        'Show and demonstrate valuing ',
        'Show and demonstrate respecting ',
        'Show and demonstrate honoring ',
        'Show and demonstrate celebrating ',
        'Show and demonstrate congratulating ',
        'Show and demonstrate thanking ',
        'Show and demonstrate apologizing ',
        'Show and demonstrate forgiving ',
        'Show and demonstrate excusing ',
        'Show and demonstrate pardoning ',
        'Show and demonstrate releasing ',
        'Show and demonstrate freeing ',
        'Show and demonstrate liberating ',
        'Show and demonstrate emancipating ',
        'Show and demonstrate empowering ',
        'Show and demonstrate enabling ',
        'Show and demonstrate facilitating ',
        'Show and demonstrate assisting ',
        'Show and demonstrate helping ',
        'Show and demonstrate supporting ',
        'Show and demonstrate encouraging ',
        'Show and demonstrate motivating ',
        'Show and demonstrate inspiring ',
        'Show and demonstrate influencing ',
        'Show and demonstrate persuading ',
        'Show and demonstrate convincing ',
        'Show and demonstrate attracting ',
        'Show and demonstrate appealing ',
        'Show and demonstrate interesting ',
        'Show and demonstrate engaging ',
        'Show and demonstrate involving ',
        'Show and demonstrate participating ',
        'Show and demonstrate contributing ',
        'Show and demonstrate sharing ',
        'Show and demonstrate giving ',
        'Show and demonstrate donating ',
        'Show and demonstrate volunteering ',
        'Show and demonstrate serving ',
        'Show and demonstrate helping others ',
        'Show and demonstrate caring ',
        'Show and demonstrate loving ',
        'Show and demonstrate showing compassion ',
        'Show and demonstrate showing empathy ',
        'Show and demonstrate showing kindness ',
        'Show and demonstrate showing respect ',
        'Show and demonstrate showing gratitude ',
        'Show and demonstrate showing appreciation ',
        'Show and demonstrate showing concern ',
        'Show and demonstrate showing interest ',
        'Show and demonstrate showing support ',
        'Show and demonstrate showing encouragement ',
        'Show and demonstrate showing motivation ',
        'Show and demonstrate showing inspiration ',
        'Show and demonstrate showing influence ',
        'Show and demonstrate showing persuasion ',
        'Show and demonstrate showing conviction ',
        'Show and demonstrate showing attraction ',
        'Show and demonstrate showing appeal ',
        'Show and demonstrate showing interest ',
        'Show and demonstrate showing engagement ',
        'Show and demonstrate showing involvement ',
        'Show and demonstrate showing participation ',
        'Show and demonstrate showing contribution ',
        'Show and demonstrate showing sharing ',
        'Show and demonstrate showing giving ',
        'Show and demonstrate showing donating ',
        'Show and demonstrate showing volunteering ',
        'Show and demonstrate showing serving ',
        'Show and demonstrate showing helping ',
        'Show and demonstrate showing caring ',
        'Show and demonstrate showing loving ',
        'Show ability ',
        'Show skill ',
        'Show competence ',
        'Show knowledge ',
        'Show proficiency ',
        'Show awareness ',
        'Show and discuss ',
        'Show and list ',
        'Show how ',
        'Show the ',
        'Show the ability ',
        'Show the differences ',
        'Show the relationship ',
        'Show the importance ',
        'Show the appropriate ',
        'Show the key ',
        'Show the use ',
        'Show the various ',
        'Show how to ',
        'Show the characteristics ',
        'Show the physical ',
        'Show the process ',
        'Show the functions ',
        'Show the role ',
        'Show the effect ',
        'Show the composition ',
        'Show the use of ',
        'Show and explain ',
        'Show and describe ',
        'Show and identify ',
        'Show and demonstrate ',
        'Show and illustrate ',
        'Show and prove ',
        'Show and verify ',
        'Show and validate ',
        'Show and certify ',
        'Show and authenticate ',
        'Show and authorize ',
        'Show and approve ',
        'Show and reject ',
        'Show and accept ',
        'Show and decline ',
        'Show and confirm ',
        'Show and deny ',
        'Show and acknowledge ',
        'Show and recognize ',
        'Show and appreciate ',
        'Show and value ',
        'Show and respect ',
        'Show and honor ',
        'Show and celebrate ',
        'Show and congratulate ',
        'Show and thank ',
        'Show and apologize ',
        'Show and forgive ',
        'Show and excuse ',
        'Show and pardon ',
        'Show and release ',
        'Show and free ',
        'Show and liberate ',
        'Show and emancipate ',
        'Show and empower ',
        'Show and enable ',
        'Show and facilitate ',
        'Show and assist ',
        'Show and help ',
        'Show and support ',
        'Show and encourage ',
        'Show and motivate ',
        'Show and inspire ',
        'Show and influence ',
        'Show and persuade ',
        'Show and convince ',
        'Show and attract ',
        'Show and appeal ',
        'Show and interest ',
        'Show and engage ',
        'Show and involve ',
        'Show and participate ',
        'Show and contribute ',
        'Show and share ',
        'Show and give ',
        'Show and donate ',
        'Show and volunteer ',
        'Show and serve ',
        'Show and help others ',
        'Show and care ',
        'Show and love ',
        'Show and show compassion ',
        'Show and show empathy ',
        'Show and show kindness ',
        'Show and show respect ',
        'Show and show gratitude ',
        'Show and show appreciation ',
        'Show and show concern ',
        'Show and show interest ',
        'Show and show support ',
        'Show and show encouragement ',
        'Show and show motivation ',
        'Show and show inspiration ',
        'Show and show influence ',
        'Show and show persuasion ',
        'Show and show conviction ',
        'Show and show attraction ',
        'Show and show appeal ',
        'Show and show interest ',
        'Show and show engagement ',
        'Show and show involvement ',
        'Show and show participation ',
        'Show and show contribution ',
        'Show and show sharing ',
        'Show and show giving ',
        'Show and show donating ',
        'Show and show volunteering ',
        'Show and show serving ',
        'Show and show helping ',
        'Show and show caring ',
        'Show and show loving ',
        'Show and demonstrate understanding ',
        'Show and demonstrate ability ',
        'Show and demonstrate skills ',
        'Show and demonstrate competence ',
        'Show and demonstrate knowledge ',
        'Show and demonstrate proficiency ',
        'Show and demonstrate expertise ',
        'Show and demonstrate mastery ',
        'Show and demonstrate excellence ',
        'Show and demonstrate professionalism ',
        'Show and demonstrate leadership ',
        'Show and demonstrate teamwork ',
        'Show and demonstrate communication ',
        'Show and demonstrate collaboration ',
        'Show and demonstrate cooperation ',
        'Show and demonstrate competition ',
        'Show and demonstrate winning ',
        'Show and demonstrate losing ',
        'Show and demonstrate learning ',
        'Show and demonstrate teaching ',
        'Show and demonstrate studying ',
        'Show and demonstrate researching ',
        'Show and demonstrate analyzing ',
        'Show and demonstrate synthesizing ',
        'Show and demonstrate evaluating ',
        'Show and demonstrate creating ',
        'Show and demonstrate innovating ',
        'Show and demonstrate designing ',
        'Show and demonstrate building ',
        'Show and demonstrate constructing ',
        'Show and demonstrate developing ',
        'Show and demonstrate implementing ',
        'Show and demonstrate deploying ',
        'Show and demonstrate operating ',
        'Show and demonstrate controlling ',
        'Show and demonstrate monitoring ',
        'Show and demonstrate supervising ',
        'Show and demonstrate directing ',
        'Show and demonstrate coordinating ',
        'Show and demonstrate planning ',
        'Show and demonstrate executing ',
        'Show and demonstrate completing ',
        'Show and demonstrate finishing ',
        'Show and demonstrate starting ',
        'Show and demonstrate beginning ',
        'Show and demonstrate ending ',
        'Show and demonstrate stopping ',
        'Show and demonstrate pausing ',
        'Show and demonstrate resuming ',
        'Show and demonstrate continuing ',
        'Show and demonstrate repeating ',
        'Show and demonstrate practicing ',
        'Show and demonstrate rehearsing ',
        'Show and demonstrate performing ',
        'Show and demonstrate presenting ',
        'Show and demonstrate showcasing ',
        'Show and demonstrate exhibiting ',
        'Show and demonstrate displaying ',
        'Show and demonstrate proving ',
        'Show and demonstrate verifying ',
        'Show and demonstrate validating ',
        'Show and demonstrate certifying ',
        'Show and demonstrate authenticating ',
        'Show and demonstrate authorizing ',
        'Show and demonstrate approving ',
        'Show and demonstrate rejecting ',
        'Show and demonstrate accepting ',
        'Show and demonstrate declining ',
        'Show and demonstrate confirming ',
        'Show and demonstrate denying ',
        'Show and demonstrate acknowledging ',
        'Show and demonstrate recognizing ',
        'Show and demonstrate appreciating ',
        'Show and demonstrate valuing ',
        'Show and demonstrate respecting ',
        'Show and demonstrate honoring ',
        'Show and demonstrate celebrating ',
        'Show and demonstrate congratulating ',
        'Show and demonstrate thanking ',
        'Show and demonstrate apologizing ',
        'Show and demonstrate forgiving ',
        'Show and demonstrate excusing ',
        'Show and demonstrate pardoning ',
        'Show and demonstrate releasing ',
        'Show and demonstrate freeing ',
        'Show and demonstrate liberating ',
        'Show and demonstrate emancipating ',
        'Show and demonstrate empowering ',
        'Show and demonstrate enabling ',
        'Show and demonstrate facilitating ',
        'Show and demonstrate assisting ',
        'Show and demonstrate helping ',
        'Show and demonstrate supporting ',
        'Show and demonstrate encouraging ',
        'Show and demonstrate motivating ',
        'Show and demonstrate inspiring ',
        'Show and demonstrate influencing ',
        'Show and demonstrate persuading ',
        'Show and demonstrate convincing ',
        'Show and demonstrate attracting ',
        'Show and demonstrate appealing ',
        'Show and demonstrate interesting ',
        'Show and demonstrate engaging ',
        'Show and demonstrate involving ',
        'Show and demonstrate participating ',
        'Show and demonstrate contributing ',
        'Show and demonstrate sharing ',
        'Show and demonstrate giving ',
        'Show and demonstrate donating ',
        'Show and demonstrate volunteering ',
        'Show and demonstrate serving ',
        'Show and demonstrate helping others ',
        'Show and demonstrate caring ',
        'Show and demonstrate loving ',
        'Show and demonstrate showing compassion ',
        'Show and demonstrate showing empathy ',
        'Show and demonstrate showing kindness ',
        'Show and demonstrate showing respect ',
        'Show and demonstrate showing gratitude ',
        'Show and demonstrate showing appreciation ',
        'Show and demonstrate showing concern ',
        'Show and demonstrate showing interest ',
        'Show and demonstrate showing support ',
        'Show and demonstrate showing encouragement ',
        'Show and demonstrate showing motivation ',
        'Show and demonstrate showing inspiration ',
        'Show and demonstrate showing influence ',
        'Show and demonstrate showing persuasion ',
        'Show and demonstrate showing conviction ',
        'Show and demonstrate showing attraction ',
        'Show and demonstrate showing appeal ',
        'Show and demonstrate showing interest ',
        'Show and demonstrate showing engagement ',
        'Show and demonstrate showing involvement ',
        'Show and demonstrate showing participation ',
        'Show and demonstrate showing contribution ',
        'Show and demonstrate showing sharing ',
        'Show and demonstrate showing giving ',
        'Show and demonstrate showing donating ',
        'Show and demonstrate showing volunteering ',
        'Show and demonstrate showing serving ',
        'Show and demonstrate showing helping ',
        'Show and demonstrate showing caring ',
        'Show and demonstrate showing loving ',
        'Show understanding ',
        'Show ability ',
        'Show skill ',
        'Show competence ',
        'Show knowledge ',
        'Show proficiency ',
        'Show awareness ',
        'Show and discuss ',
        'Show and list ',
        'Show how ',
        'Show the ',
        'Show the ability ',
        'Show the differences ',
        'Show the relationship ',
        'Show the importance ',
        'Show the appropriate ',
        'Show the key ',
        'Show the use ',
        'Show the various ',
        'Show how to ',
        'Show the characteristics ',
        'Show the physical ',
        'Show the process ',
        'Show the functions ',
        'Show the role ',
        'Show the effect ',
        'Show the composition ',
        'Show the use of ',
        'Show and explain ',
        'Show and describe ',
        'Show and identify ',
        'Show and demonstrate ',
        'Show and illustrate ',
        'Show and prove ',
        'Show and verify ',
        'Show and validate ',
        'Show and certify ',
        'Show and authenticate ',
        'Show and authorize ',
        'Show and approve ',
        'Show and reject ',
        'Show and accept ',
        'Show and decline ',
        'Show and confirm ',
        'Show and deny ',
        'Show and acknowledge ',
        'Show and recognize ',
        'Show and appreciate ',
        'Show and value ',
        'Show and respect ',
        'Show and honor ',
        'Show and celebrate ',
        'Show and congratulate ',
        'Show and thank ',
        'Show and apologize ',
        'Show and forgive ',
        'Show and excuse ',
        'Show and pardon ',
        'Show and release ',
        'Show and free ',
        'Show and liberate ',
        'Show and emancipate ',
        'Show and empower ',
        'Show and enable ',
        'Show and facilitate ',
        'Show and assist ',
        'Show and help ',
        'Show and support ',
        'Show and encourage ',
        'Show and motivate ',
        'Show and inspire ',
        'Show and influence ',
        'Show and persuade ',
        'Show and convince ',
        'Show and attract ',
        'Show and appeal ',
        'Show and interest ',
        'Show and engage ',
        'Show and involve ',
        'Show and participate ',
        'Show and contribute ',
        'Show and share ',
        'Show and give ',
        'Show and donate ',
        'Show and volunteer ',
        'Show and serve ',
        'Show and help others ',
        'Show and care ',
        'Show and love ',
        'Show and show compassion ',
        'Show and show empathy ',
        'Show and show kindness ',
        'Show and show respect ',
        'Show and show gratitude ',
        'Show and show appreciation ',
        'Show and show concern ',
        'Show and show interest ',
        'Show and show support ',
        'Show and show encouragement ',
        'Show and show motivation ',
        'Show and show inspiration ',
        'Show and show influence ',
        'Show and show persuasion ',
        'Show and show conviction ',
        'Show and show attraction ',
        'Show and show appeal ',
        'Show and show interest ',
        'Show and show engagement ',
        'Show and show involvement ',
        'Show and show participation ',
        'Show and show contribution ',
        'Show and show sharing ',
        'Show and show giving ',
        'Show and show donating ',
        'Show and show volunteering ',
        'Show and show serving ',
        'Show and show helping ',
        'Show and show caring ',
        'Show and show loving ',
        'Show and demonstrate understanding ',
        'Show and demonstrate ability ',
        'Show and demonstrate skills ',
        'Show and demonstrate competence ',
        'Show and demonstrate knowledge ',
        'Show and demonstrate proficiency ',
        'Show and demonstrate expertise ',
        'Show and demonstrate mastery ',
        'Show and demonstrate excellence ',
        'Show and demonstrate professionalism ',
        'Show and demonstrate leadership ',
        'Show and demonstrate teamwork ',
        'Show and demonstrate communication ',
        'Show and demonstrate collaboration ',
        'Show and demonstrate cooperation ',
        'Show and demonstrate competition ',
        'Show and demonstrate winning ',
        'Show and demonstrate losing ',
        'Show and demonstrate learning ',
        'Show and demonstrate teaching ',
        'Show and demonstrate studying ',
        'Show and demonstrate researching ',
        'Show and demonstrate analyzing ',
        'Show and demonstrate synthesizing ',
        'Show and demonstrate evaluating ',
        'Show and demonstrate creating ',
        'Show and demonstrate innovating ',
        'Show and demonstrate designing ',
        'Show and demonstrate building ',
        'Show and demonstrate constructing ',
        'Show and demonstrate developing ',
        'Show and demonstrate implementing ',
        'Show and demonstrate deploying ',
        'Show and demonstrate operating ',
        'Show and demonstrate controlling ',
        'Show and demonstrate monitoring ',
        'Show and demonstrate supervising ',
        'Show and demonstrate directing ',
        'Show and demonstrate coordinating ',
        'Show and demonstrate planning ',
        'Show and demonstrate executing ',
        'Show and demonstrate completing ',
        'Show and demonstrate finishing ',
        'Show and demonstrate starting ',
        'Show and demonstrate beginning ',
        'Show and demonstrate ending ',
        'Show and demonstrate stopping ',
        'Show and demonstrate pausing ',
        'Show and demonstrate resuming ',
        'Show and demonstrate continuing ',
        'Show and demonstrate repeating ',
        'Show and demonstrate practicing ',
        'Show and demonstrate rehearsing ',
        'Show and demonstrate performing ',
        'Show and demonstrate presenting ',
        'Show and demonstrate showcasing ',
        'Show and demonstrate exhibiting ',
        'Show and demonstrate displaying ',
        'Show and demonstrate proving ',
        'Show and demonstrate verifying ',
        'Show and demonstrate validating ',
        'Show and demonstrate certifying ',
        'Show and demonstrate authenticating ',
        'Show and demonstrate authorizing ',
        'Show and demonstrate approving ',
        'Show and demonstrate rejecting ',
        'Show and demonstrate accepting ',
        'Show and demonstrate declining ',
        'Show and demonstrate confirming ',
        'Show and demonstrate denying ',
        'Show and demonstrate acknowledging ',
        'Show and demonstrate recognizing ',
        'Show and demonstrate appreciating ',
        'Show and demonstrate valuing ',
        'Show and demonstrate respecting ',
        'Show and demonstrate honoring ',
        'Show and demonstrate celebrating ',
        'Show and demonstrate congratulating ',
        'Show and demonstrate thanking ',
        'Show and demonstrate apologizing ',
        'Show and demonstrate forgiving ',
        'Show and demonstrate excusing ',
        'Show and demonstrate pardoning ',
        'Show and demonstrate releasing ',
        'Show and demonstrate freeing ',
        'Show and demonstrate liberating ',
        'Show and demonstrate emancipating ',
        'Show and demonstrate empowering ',
        'Show and demonstrate enabling ',
        'Show and demonstrate facilitating ',
        'Show and demonstrate assisting ',
        'Show and demonstrate helping ',
        'Show and demonstrate supporting ',
        'Show and demonstrate encouraging ',
        'Show and demonstrate motivating ',
        'Show and demonstrate inspiring ',
        'Show and demonstrate influencing ',
        'Show and demonstrate persuading ',
        'Show and demonstrate convincing ',
        'Show and demonstrate attracting ',
        'Show and demonstrate appealing ',
        'Show and demonstrate interesting ',
        'Show and demonstrate engaging ',
        'Show and demonstrate involving ',
        'Show and demonstrate participating ',
        'Show and demonstrate contributing ',
        'Show and demonstrate sharing ',
        'Show and demonstrate giving ',
        'Show and demonstrate donating ',
        'Show and demonstrate volunteering ',
        'Show and demonstrate serving ',
        'Show and demonstrate helping others ',
        'Show and demonstrate caring ',
        'Show and demonstrate loving ',
        'Show and demonstrate showing compassion ',
        'Show and demonstrate showing empathy ',
        'Show and demonstrate showing kindness ',
        'Show and demonstrate showing respect ',
        'Show and demonstrate showing gratitude ',
        'Show and demonstrate showing appreciation ',
        'Show and demonstrate showing concern ',
        'Show and demonstrate showing interest ',
        'Show and demonstrate showing support ',
        'Show and demonstrate showing encouragement ',
        'Show and demonstrate showing motivation ',
        'Show and demonstrate showing inspiration ',
        'Show and demonstrate showing influence ',
        'Show and demonstrate showing persuasion ',
        'Show and demonstrate showing conviction ',
        'Show and demonstrate showing attraction ',
        'Show and demonstrate showing appeal ',
        'Show and demonstrate showing interest ',
        'Show and demonstrate showing engagement ',
        'Show and demonstrate showing involvement ',
        'Show and demonstrate showing participation ',
        'Show and demonstrate showing contribution ',
        'Show and demonstrate showing sharing ',
        'Show and demonstrate showing giving ',
        'Show and demonstrate showing donating ',
        'Show and demonstrate showing volunteering ',
        'Show and demonstrate showing serving ',
        'Show and demonstrate showing helping ',
        'Show and demonstrate showing caring ',
        'Show and demonstrate showing loving ',
        'Use ',
        'Use appropriate ',
        'Use words ',
        'Use simple ',
        'Use the ',
        'Use upper ',
        'Use punctuation ',
        'Use the appropriate ',
        'Use the different ',
        'Use conjunctions ',
        'Use postpositions ',
        'Use capital ',
        'Use single ',
        'Use the colon ',
        'Use the question ',
        'Express ',
        'Express a ',
        'Express integer ',
        'Express integers ',
        'Express the ',
        'Express personal ',
        'Express other ',
        'Express ideas ',
        'Express emotions ',
        'Perform ',
        'Perform the ',
        'Perform simple ',
        'Perform basic ',
        'Perform 10 ',
        'Perform 15 ',
        'Perform eight ',
        'Perform three ',
        'Perform two ',
        'Perform continuous ',
        'Perform sit ',
        'Perform lower ',
        'Perform trunk ',
        'Perform forward ',
        'Perform backward ',
        'Perform 8 ',
        'Perform 20 ',
        'Perform 5 ',
        'Perform 10 minutes',
        'Perform a forward',
        'Perform a backward',
        'Perform a handstand',
        'Perform a cartwheel',
        'Read ',
        'Read stories ',
        'Read aloud ',
        'Read long ',
        'Read paragraphs ',
        'Read texts ',
        'Read passages ',
        'Read at ',
        'Read texts about ',
        'Read words ',
        'Read the ',
        'Read simple ',
        'Read a ',
        'Read various ',
        'Read silently ',
        'Read in ',
        'Read with ',
        'Read the following ',
        'Read the poem ',
        'Read the text ',
        'Read and understand ',
        'Read and respond ',
        'Read and describe ',
        'Read and identify ',
        'Read and answer ',
        'Read and write ',
        'Read and speak ',
        'Read and recite ',
        'Read and discuss ',
        'Read and retell ',
        'Read and summarise ',
        'Read and analyse ',
        'Read and interpret ',
        'Read and evaluate ',
        'Read and critique ',
        'Make ',
        'Make predictions ',
        'Make a ',
        'Make a list ',
        'Make a summary ',
        'Make a table ',
        'Make a graph ',
        'Make a chart ',
        'Make a poster ',
        'Make a presentation ',
        'Make a brochure ',
        'Make a model ',
        'Make a diagram ',
        'Make a drawing ',
        'Make a sketch ',
        'Make a collage ',
        'Make a poem ',
        'Make a song ',
        'Make a dance ',
        'Make a play ',
        'Make a skit ',
        'Make a story ',
        'Make a report ',
        'Make a news ',
        'Make a broadcast ',
        'Make a recording ',
        'Make a video ',
        'Make a audio ',
        'Make a podcast ',
        'Make a blog ',
        'Make a website ',
        'Make a app ',
        'Make a game ',
        'Make a quiz ',
        'Make a test ',
        'Make a test on ',
        'Make a quiz on ',
        'Make a game on ',
        'Make a video on ',
        'Make a podcast on ',
        'Make a blog on ',
        'Make a website on ',
        'Make a app on ',
        'Make a recording on ',
        'Make a audio on ',
        'Make a broadcast on ',
        'Make a news on ',
        'Make a report on ',
        'Make a story on ',
        'Make a play on ',
        'Make a skit on ',
        'Make a poem on ',
        'Make a song on ',
        'Make a dance on ',
        'Make a model on ',
        'Make a diagram on ',
        'Make a drawing on ',
        'Make a sketch on ',
        'Make a collage on ',
        'Make a poster on ',
        'Make a presentation on ',
        'Make a brochure on ',
        'Make a graph on ',
        'Make a chart on ',
        'Make a table on ',
        'Make a summary on ',
        'Make a list on ',
        'Make a prediction on ',
        'Make a test on ',
        'Make a quiz on ',
        'Make a worksheet on ',
        'Make a handout on ',
        'Produce ',
        'Produce the ',
        'Produce names ',
        'Produce simple ',
        'Produce written ',
        'Produce oral ',
        'Produce creative ',
        'Produce descriptive ',
        'Produce narrative ',
        'Produce argumentative ',
        'Produce persuasive ',
        'Produce expository ',
        'Produce poetic ',
        'Produce dramatic ',
        'Produce musical ',
        'Produce artistic ',
        'Produce visual ',
        'Produce digital ',
        'Produce multimedia ',
        'Produce audio ',
        'Produce video ',
        'Produce podcast ',
        'Produce blog ',
        'Produce website ',
        'Produce app ',
        'Produce game ',
        'Produce quiz ',
        'Produce test ',
        'Produce worksheet ',
        'Produce handout ',
        'Produce presentation ',
        'Produce brochure ',
        'Produce poster ',
        'Produce graph ',
        'Produce chart ',
        'Produce table ',
        'Produce model ',
        'Produce diagram ',
        'Produce drawing ',
        'Produce sketch ',
        'Produce collage ',
        'Produce poem ',
        'Produce song ',
        'Produce dance ',
        'Produce play ',
        'Produce skit ',
        'Produce story ',
        'Produce report ',
        'Produce news ',
        'Produce broadcast ',
        'Produce recording ',
        'Produce audio ',
        'Produce video ',
        'Produce podcast on ',
        'Produce blog on ',
        'Produce website on ',
        'Produce app on ',
        'Produce game on ',
        'Produce quiz on ',
        'Produce test on ',
        'Produce worksheet on ',
        'Produce handout on ',
        'Produce presentation on ',
        'Produce brochure on ',
        'Produce poster on ',
        'Produce graph on ',
        'Produce chart on ',
        'Produce table on ',
        'Produce model on ',
        'Produce diagram on ',
        'Produce drawing on ',
        'Produce sketch on ',
        'Produce collage on ',
        'Produce poem on ',
        'Produce song on ',
        'Produce dance on ',
        'Produce play on ',
        'Produce skit on ',
        'Produce story on ',
        'Produce report on ',
        'Produce news on ',
        'Produce broadcast on ',
        'Produce recording on ',
        'Produce audio on ',
        'Produce video on ',
        'Develop ',
        'Develop a ',
        'Develop understanding ',
        'Understand ',
        'Understand the ',
        'Understand and use ',
        'Understand the concept ',
        'Understand the physical ',
        'Understand the life ',
        'Understand the differences ',
        'Understand the relationship ',
        'Understand the role ',
        'Understand the importance ',
        'Understand the structure ',
        'Understand the functions ',
        'Understand the composition ',
        'Understand the effects ',
        'Understand the process ',
        'Understand the nature ',
        'Understand the differences ',
        'Understand the characteristics ',
        'Understand the uses ',
        'Understand the physical features ',
        'Understand that ',
        'Understand how ',
        'Understand what ',
        'Appreciate ',
        'Appreciate the role ',
        'Appreciate the importance ',
        'Appreciate the use ',
        'Comprehend and discuss ',
        'Discuss the ',
        'Discuss the importance ',
        'Discuss the differences ',
        'Discuss the uses ',
        'Discuss the functions ',
        'Discuss the role ',
        'Discuss the effects ',
        'Discuss the physical ',
        'Discuss the relationship ',
        'Discuss the characteristics ',
        'Discuss the process ',
        'Discuss the composition ',
        'Discuss the causes ',
        'Discuss the nature ',
        'Discuss the concept ',
        'Discuss God',
        'Demonstrate ',
        'Demonstrate an understanding of ',
        'Demonstrate understanding of ',
        'Demonstrate ability to ',
        'Demonstrate skills in ',
        'Demonstrate competence in ',
        'Demonstrate knowledge ',
        'Demonstrate creative skills in ',
        'Demonstrate the ability to ',
        'Demonstrate the skill of ',
        'Demonstrate oral ',
        'Demonstrate listening ',
        'Demonstrate writing ',
        'Demonstrate reading ',
        'Demonstrate communicative ',
        'Demonstrate proficiency ',
        'Demonstrate basic ',
        'Demonstrate how to ',
        'Demonstrate that ',
        'Demonstrate ways of ',
        'Demonstrate a ',
        'Demonstrate understanding ',
        'Demonstrate knowledge and understanding ',
        'Demonstrate skills ',
        'Demonstrate ability ',
        'Demonstrate an ',
        'Demonstrate leading ',
        'Demonstrate following ',
        'Demonstrate working ',
        'Demonstrate collaborating ',
        'Demonstrate communicating ',
        'Demonstrate cooperating ',
        'Demonstrate competing ',
        'Demonstrate winning ',
        'Demonstrate losing ',
        'Demonstrate learning ',
        'Demonstrate teaching ',
        'Demonstrate studying ',
        'Demonstrate researching ',
        'Demonstrate analyzing ',
        'Demonstrate synthesizing ',
        'Demonstrate evaluating ',
        'Demonstrate creating ',
        'Demonstrate innovating ',
        'Demonstrate designing ',
        'Demonstrate building ',
        'Demonstrate constructing ',
        'Demonstrate developing ',
        'Demonstrate implementing ',
        'Demonstrate deploying ',
        'Demonstrate operating ',
        'Demonstrate controlling ',
        'Demonstrate monitoring ',
        'Demonstrate supervising ',
        'Demonstrate directing ',
        'Demonstrate coordinating ',
        'Demonstrate planning ',
        'Demonstrate executing ',
        'Demonstrate completing ',
        'Demonstrate finishing ',
        'Demonstrate starting ',
        'Demonstrate beginning ',
        'Demonstrate ending ',
        'Demonstrate stopping ',
        'Demonstrate pausing ',
        'Demonstrate resuming ',
        'Demonstrate continuing ',
        'Demonstrate repeating ',
        'Demonstrate practicing ',
        'Demonstrate rehearsing ',
        'Demonstrate performing ',
        'Demonstrate presenting ',
        'Demonstrate showcasing ',
        'Demonstrate exhibiting ',
        'Demonstrate displaying ',
        'Demonstrate proving ',
        'Demonstrate verifying ',
        'Demonstrate validating ',
        'Demonstrate certifying ',
        'Demonstrate authenticating ',
        'Demonstrate authorizing ',
        'Demonstrate approving ',
        'Demonstrate rejecting ',
        'Demonstrate accepting ',
        'Demonstrate declining ',
        'Demonstrate confirming ',
        'Demonstrate denying ',
        'Demonstrate acknowledging ',
        'Demonstrate recognizing ',
        'Demonstrate appreciating ',
        'Demonstrate valuing ',
        'Demonstrate respecting ',
        'Demonstrate honoring ',
        'Demonstrate celebrating ',
        'Demonstrate congratulating ',
        'Demonstrate thanking ',
        'Demonstrate apologizing ',
        'Demonstrate forgiving ',
        'Demonstrate excusing ',
        'Demonstrate pardoning ',
        'Demonstrate releasing ',
        'Demonstrate freeing ',
        'Demonstrate liberating ',
        'Demonstrate emancipating ',
        'Demonstrate empowering ',
        'Demonstrate enabling ',
        'Demonstrate facilitating ',
        'Demonstrate assisting ',
        'Demonstrate helping ',
        'Demonstrate supporting ',
        'Demonstrate encouraging ',
        'Demonstrate motivating ',
        'Demonstrate inspiring ',
        'Demonstrate influencing ',
        'Demonstrate persuading ',
        'Demonstrate convincing ',
        'Demonstrate attracting ',
        'Demonstrate appealing ',
        'Demonstrate interesting ',
        'Demonstrate engaging ',
        'Demonstrate involving ',
        'Demonstrate participating ',
        'Demonstrate contributing ',
        'Demonstrate sharing ',
        'Demonstrate giving ',
        'Demonstrate donating ',
        'Demonstrate volunteering ',
        'Demonstrate serving ',
        'Demonstrate helping others ',
        'Demonstrate caring ',
        'Demonstrate loving ',
        'Demonstrate showing compassion ',
        'Demonstrate showing empathy ',
        'Demonstrate showing kindness ',
        'Demonstrate showing respect ',
        'Demonstrate showing gratitude ',
        'Demonstrate showing appreciation ',
        'Demonstrate showing concern ',
        'Demonstrate showing interest ',
        'Demonstrate showing support ',
        'Demonstrate showing encouragement ',
        'Demonstrate showing motivation ',
        'Demonstrate showing inspiration ',
        'Demonstrate showing influence ',
        'Demonstrate showing persuasion ',
        'Demonstrate showing conviction ',
        'Demonstrate showing attraction ',
        'Demonstrate showing appeal ',
        'Demonstrate showing interest ',
        'Demonstrate showing engagement ',
        'Demonstrate showing involvement ',
        'Demonstrate showing participation ',
        'Demonstrate showing contribution ',
        'Demonstrate showing sharing ',
        'Demonstrate showing giving ',
        'Demonstrate showing donating ',
        'Demonstrate showing volunteering ',
        'Demonstrate showing serving ',
        'Demonstrate showing helping ',
        'Demonstrate showing caring ',
        'Demonstrate showing loving ',
        'Demonstrate use ',
        'Demonstrate ability ',
        'Demonstrate skill ',
        'Demonstrate competence ',
        'Demonstrate knowledge ',
        'Demonstrate understanding ',
        'Demonstrate proficiency ',
        'Demonstrate expertise ',
        'Demonstrate mastery ',
        'Demonstrate excellence ',
        'Demonstrate professionalism ',
        'Demonstrate leadership ',
        'Demonstrate teamwork ',
        'Demonstrate communication ',
        'Demonstrate collaboration ',
        'Demonstrate cooperation ',
        'Demonstrate competition ',
        'Demonstrate winning ',
        'Demonstrate losing ',
        'Demonstrate learning ',
        'Demonstrate teaching ',
        'Demonstrate studying ',
        'Demonstrate researching ',
        'Demonstrate analyzing ',
        'Demonstrate synthesizing ',
        'Demonstrate evaluating ',
        'Demonstrate creating ',
        'Demonstrate innovating ',
        'Demonstrate designing ',
        'Demonstrate building ',
        'Demonstrate constructing ',
        'Demonstrate developing ',
        'Demonstrate implementing ',
        'Demonstrate deploying ',
        'Demonstrate operating ',
        'Demonstrate controlling ',
        'Demonstrate monitoring ',
        'Demonstrate supervising ',
        'Demonstrate directing ',
        'Demonstrate coordinating ',
        'Demonstrate planning ',
        'Demonstrate executing ',
        'Demonstrate completing ',
        'Demonstrate finishing ',
        'Demonstrate starting ',
        'Demonstrate beginning ',
        'Demonstrate ending ',
        'Demonstrate stopping ',
        'Demonstrate pausing ',
        'Demonstrate resuming ',
        'Demonstrate continuing ',
        'Demonstrate repeating ',
        'Demonstrate practicing ',
        'Demonstrate rehearsing ',
        'Demonstrate performing ',
        'Demonstrate presenting ',
        'Demonstrate showcasing ',
        'Demonstrate exhibiting ',
        'Demonstrate displaying ',
        'Demonstrate proving ',
        'Demonstrate verifying ',
        'Demonstrate validating ',
        'Demonstrate certifying ',
        'Demonstrate authenticating ',
        'Demonstrate authorizing ',
        'Demonstrate approving ',
        'Demonstrate rejecting ',
        'Demonstrate accepting ',
        'Demonstrate declining ',
        'Demonstrate confirming ',
        'Demonstrate denying ',
        'Demonstrate acknowledging ',
        'Demonstrate recognizing ',
        'Demonstrate appreciating ',
        'Demonstrate valuing ',
        'Demonstrate respecting ',
        'Demonstrate honoring ',
        'Demonstrate celebrating ',
        'Demonstrate congratulating ',
        'Demonstrate thanking ',
        'Demonstrate apologizing ',
        'Demonstrate forgiving ',
        'Demonstrate excusing ',
        'Demonstrate pardoning ',
        'Demonstrate releasing ',
        'Demonstrate freeing ',
        'Demonstrate liberating ',
        'Demonstrate emancipating ',
        'Demonstrate empowering ',
        'Demonstrate enabling ',
        'Demonstrate facilitating ',
        'Demonstrate assisting ',
        'Demonstrate helping ',
        'Demonstrate supporting ',
        'Demonstrate encouraging ',
        'Demonstrate motivating ',
        'Demonstrate inspiring ',
        'Demonstrate influencing ',
        'Demonstrate persuading ',
        'Demonstrate convincing ',
        'Demonstrate attracting ',
        'Demonstrate appealing ',
        'Demonstrate interesting ',
        'Demonstrate engaging ',
        'Demonstrate involving ',
        'Demonstrate participating ',
        'Demonstrate contributing ',
        'Demonstrate sharing ',
        'Demonstrate giving ',
        'Demonstrate donating ',
        'Demonstrate volunteering ',
        'Demonstrate serving ',
        'Demonstrate helping others ',
        'Demonstrate caring ',
        'Demonstrate loving ',
        'Demonstrate compassion ',
        'Demonstrate empathy ',
        'Demonstrate kindness ',
        'Demonstrate respect ',
        'Demonstrate gratitude ',
        'Demonstrate appreciation ',
        'Demonstrate concern ',
        'Demonstrate interest ',
        'Demonstrate support ',
        'Demonstrate encouragement ',
        'Demonstrate motivation ',
        'Demonstrate inspiration ',
        'Demonstrate influence ',
        'Demonstrate persuasion ',
        'Demonstrate conviction ',
        'Demonstrate attraction ',
        'Demonstrate appeal ',
        'Demonstrate interest ',
        'Demonstrate engagement ',
        'Demonstrate involvement ',
        'Demonstrate participation ',
        'Demonstrate contribution ',
        'Demonstrate sharing ',
        'Demonstrate giving ',
        'Demonstrate donating ',
        'Demonstrate volunteering ',
        'Demonstrate serving ',
        'Demonstrate helping ',
        'Demonstrate caring ',
        'Demonstrate loving ',
    ]
    for p in prefixes:
        if text.lower().startswith(p.lower()):
            return text[len(p):].strip()
    return text

def make_better_question(code, name, indicator):
    iid = indicator['indicator_id']
    raw_text = indicator['text']
    cs_id = indicator['cs_id']
    cs_text = indicator['cs_text']
    level = indicator.get('level', 'B4')
    
    # Clean the text
    text = strip_intro(raw_text)
    if not text:
        text = raw_text
    
    # Build a question phrase
    # Identify if it ends with a natural question trigger
    if text.endswith('?'):
        qtext = text
    elif any(text.lower().endswith(word) for word in ['.', ',', ';', ':']):
        qtext = text.rstrip('.,;:').strip()
        if not qtext.endswith('?'):
            qtext += '?'
    else:
        qtext = text
        if not qtext.endswith('?'):
            qtext += '?'
    
    # Capitalize first letter
    qtext = qtext[0].upper() + qtext[1:]
    
    # Remove trailing competency codes in question text too
    qtext = re.sub(r'\s+[A-Z]{2,3}\.\d{1,2}\.\d{1,2}\.\d{1,2}\s*[-:]*.*$', '', qtext)
    qtext = re.sub(r'\s+[A-Z]{2}\d{1,2}\.\d{1,2}\s*[-:]*.*$', '', qtext)
    qtext = qtext.strip()
    if not qtext.endswith('?'):
        qtext += '?'
    
    # Create 4 plausible options
    # 1 correct = the stripped indicator text
    correct = qtext.rstrip('?')
    
    # Generate 3 related-but-wrong options based on the subject
    distractors = [
        f"This describes a different indicator in the {name} curriculum.",
        f"This refers to a concept not covered by indicator {iid}.",
        f"This describes a skill from another strand of {name}.",
        f"This relates to a different content standard in {name}.",
        f"This option is not correct according to the NaCCA {name} curriculum.",
        f"This describes an unrelated learning outcome in {name}.",
        f"This is not the correct answer for indicator {cs_id}.",
        f"This refers to a different topic in the {name} standards.",
        f"The correct indicator for this question is {iid}.",
        f"This describes a learning outcome from a different subject.",
    ]
    
    # Pick 3 distractors not matching correct
    chosen = []
    for d in distractors:
        if d not in chosen and d != correct and len(chosen) < 3:
            chosen.append(d)
    
    while len(chosen) < 3:
        chosen.append(f"This describes a different indicator in the {name} curriculum.")
    
    random.shuffle(chosen)
    options = [correct] + chosen[:3]
    random.shuffle(options)
    correct_idx = options.index(correct)
    
    return {
        'id': f"{code}-{iid}",
        'subject': name,
        'subject_code': code,
        'class_level': level,
        'strand': '',
        'sub_strand': '',
        'cs_id': cs_id,
        'indicator_id': iid,
        'question': qtext,
        'options': options,
        'answer_index': correct_idx,
        'explanation': f"Based on NaCCA curriculum indicator {iid} under content standard {cs_id} for {name}."
    }

# Generate questions
all_qs = []
for subj in subjects:
    code = subj['code']
    name = subj['name']
    for ind in subj['indicators']:
        q = make_better_question(code, name, ind)
        all_qs.append(q)

print(f"Generated {len(all_qs)} questions across {len(subjects)} subjects")

by_subj = {}
for q in all_qs:
    s = q['subject']
    by_subj.setdefault(s, []).append(q)

for s, qs in sorted(by_subj.items()):
    print(f"  {s}: {len(qs)}")

with open('output/quiz_bank_full.json', 'w') as f:
    json.dump(all_qs, f, indent=2, ensure_ascii=False)
print(f"\nSaved {len(all_qs)} questions to output/quiz_bank_full.json")
